config/routes.rb
Omrails::Application.routes.draw do

  devise_for :users

  root :to => 'pages#home'

  get "about" => "pages#about"

  get "sommerakademie" => "pages#sommerakademie"  

  get "cirkusschule" => "pages#cirkusschule"

  get "pachamama" => "pages#pachamama"

end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :token_authenticatable, :confirmable,
  # :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  # Setup accessible (or protected) attributes for your model
  attr_accessible :email, :password, :password_confirmation, :remember_me
  # attr_accessible :title, :body
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
  end

	def about
	end

	def sommerakademie
	end

	def cirkusschule		
	end

	def pachamama		
	end
	
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/views/layouts/_footer.html.erb
<div class="footer">
		<small>
			 <%= link_to "Internationale Sommerakademie für Theater Graz", "http://theaterakademie-graz.org" %>, <%= link_to "Cirkusschule für Kinder", "http://kindercirkusschule.org" %> and <%= link_to "Colegio PACHA MAMA", "http://www.pachamama.edu.ec/" %> are organized by "Verein FREIRÄUME". All rights reserved.
		</small>
</div>

app/views/layouts/_header.html.erb
<div class="navbar navbar-fixed-top">
  <div class="navbar-inner">
    <div class="container">
 
      <!-- .btn-navbar is used as the toggle for collapsed navbar content -->
      <a class="btn btn-navbar" data-toggle="collapse" data-target=".nav-collapse">
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </a>
 
      <!-- Be sure to leave the brand out there if you want it shown -->
      <%= link_to "Freiräume", root_path, class: "brand" %>

      <!-- Everything you want hidden at 940px or less, place within here -->
      <div class="nav-collapse collapse">
	       <ul class="nav">   
	        <li><%= link_to "Home", root_path %></li>
	        <li><%= link_to "About Us", about_path %></li>
        <!-- .nav, .navbar-search, .navbar-form, etc -->
      </div>
 
    </div>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
		<head>
		<meta name="viewport" content="width=device-width, initial-scale=1.0">
		<link href="assets/css/bootstrap-responsive.css" rel="stylesheet">
		  <title>Freiräume</title>
		  <%= stylesheet_link_tag    "application", :media => "all" %>
		  <%= javascript_include_tag "application" %>
		  <%= csrf_meta_tags %>
		</head>
	<body>
		<%= render 'layouts/header' %>
		
		<div class="container">
			<% flash.each do |name, msg| %>
                <%= content_tag(:div, msg, class: "alert alert-#{name}") %>
			<% end %>
			<%= yield %>
			<%= render 'layouts/footer' %>
		</div>
	</body>
</html>

app/views/pages/about.html.erb
<h1>About</h1>
<p>
	This is the Page of Verein FREIRÄUME, organizer of
	<p>
		<%= link_to "Internationale Sommerakademie für Theater Graz", "http://theaterakademie-graz.org" %>
	</p>
	<p>
		<%= link_to "Cirkusschule für Kinder", "http://kindercirkusschule.org" %>
	</p>
	and
	<p>
		<%= link_to "Pacha Mama", "http://www.pachamama.edu.ec/" %>
	</p>
</p>

app/views/pages/cirkusschule.html.erb
<div class="center hero-unit">	
	<h1>Cirkusschule für Kinder</h1>
	<p>
		Graz, Austria
	</p>
	<p>
		Founded an raised by Thomas Svoboda long time ago.
		Find more information on the project´s <%= link_to "homepage", "http://kindercirkusschule.org" %>
	</p>
</div>

app/views/pages/home.html.erb
<div class="center hero-unit">	
	<h1>Welcome to our project page!!</h1>
	<p>
		Verein FREIRÄUME is a benevolent association with projects in Austria and Ecuador.
	</p>
	<br>
	<br>
	<div class="row-fluid">
	  <div class="span4">
	  	<%= link_to image_tag("http://www.theaterakademie-graz.at/system/html/Musicalgruppe-58e841e9.jpg"), sommerakademie_path %>
	  	<p>
		<%= link_to "Internationale Sommerakademie für Theater", sommerakademie_path %>
		</p>
	  </div>
	  <div class="span4">
	  	<%= link_to image_tag("http://www.kindercirkusschule.org/DSC_2180.jpg"), cirkusschule_path %>
	  	<p>
		<%= link_to "Cirkusschule für Kinder", cirkusschule_path %>
		</p>
	  </div>
	  <div class="span4">
	  	<%= link_to image_tag("http://www.pachamama.edu.ec/fotos/home/home47.jpg"), pachamama_path %>
	  	<p>
		<%= link_to "Colegio PACHA MAMA - Quito", pachamama_path %>
		</p>
	  </div>
	</div>
</div>

app/views/pages/pachamama.html.erb
<div class="center hero-unit">	
	<h1>Colegio Pacha Mama!!</h1>
	<p>
		Quito, Ecuador.
	</p>
	<p>
		Founded in 1995 and since then run by Wolfgang and Veronique Gorris as a project of the ecuadorian sister association "Espacios Libres".
		Find more information on the project´s <%= link_to "homepage", "http://www.pachamama.edu.ec/" %>
	</p>
</div>

app/views/pages/sommerakademie.html.erb
<div class="center hero-unit">	
	<h1>Internationale Sommerakademie für Theater Graz!!</h1>
	<p>
		Graz, Austria
	</p>
	<p>
		Raised and organized by Thomas Svoboda since 1987. Since 2007 run as an organization comitee by Thomas Svoboda, Doris Liebl and Gregor Kleczkowski.
		Find more information on the project´s <%= link_to "homepage", "http://theaterakademie-graz.org" %>
	</p>
</div>